// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: lurking.sql

package dbgen

import (
	"context"
)

const getRedditSubredditSubscriptions = `-- name: GetRedditSubredditSubscriptions :many
SELECT name
FROM reddit_subreddit_subscriptions
`

func (q *Queries) GetRedditSubredditSubscriptions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getRedditSubredditSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedditUserSubscriptions = `-- name: GetRedditUserSubscriptions :many
SELECT name
FROM reddit_user_subscriptions
`

func (q *Queries) GetRedditUserSubscriptions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getRedditUserSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
