// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reddit-metrics.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRedditCommentMetricsByIDs = `-- name: GetRedditCommentMetricsByIDs :many
SELECT
    r.id AS "id",
    r.ts AS "ts",
    r.score::REAL AS "value",
    'reddit.comment.score' AS "metric"
FROM reddit_comment_score AS r
WHERE
    r.id = ANY($1::VARCHAR[]) AND
    r.ts >= $2 AND
    r.ts <= $3
UNION ALL
SELECT
    r.id AS "id",
    r.ts AS "ts",
    r.controversiality::REAL AS "controversiality",
    'reddit.comment.controversiality' AS "metric"
FROM reddit_comment_controversiality AS r
WHERE
    r.id = ANY($1::VARCHAR[]) AND
    r.ts >= $2 AND
    r.ts <= $3
`

type GetRedditCommentMetricsByIDsParams struct {
	Ids     []string           `json:"ids"`
	TsStart pgtype.Timestamptz `json:"ts_start"`
	TsEnd   pgtype.Timestamptz `json:"ts_end"`
}

type GetRedditCommentMetricsByIDsRow struct {
	ID     string             `json:"id"`
	Ts     pgtype.Timestamptz `json:"ts"`
	Value  float32            `json:"value"`
	Metric string             `json:"metric"`
}

func (q *Queries) GetRedditCommentMetricsByIDs(ctx context.Context, arg GetRedditCommentMetricsByIDsParams) ([]GetRedditCommentMetricsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getRedditCommentMetricsByIDs, arg.Ids, arg.TsStart, arg.TsEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRedditCommentMetricsByIDsRow
	for rows.Next() {
		var i GetRedditCommentMetricsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Value,
			&i.Metric,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedditPostMetricsByIDs = `-- name: GetRedditPostMetricsByIDs :many
SELECT
    id AS "id",
    title AS "title",
    ts AS "ts",
    score::REAL AS "value",
    'reddit.post.score' AS "metric"
FROM reddit_post_score AS r
WHERE
    r.id = ANY($1::VARCHAR[]) AND
    r.ts >= $2 AND
    r.ts <= $3
UNION ALL
SELECT
    id AS "id",
    title AS "title",
    ts AS "ts",
    ratio::REAL AS "value",
    'reddit.post.ratio' AS "metric"
FROM reddit_post_ratio AS r
WHERE
    r.id = ANY($1::VARCHAR[]) AND
    r.ts >= $2 AND
    r.ts <= $3
`

type GetRedditPostMetricsByIDsParams struct {
	Ids     []string           `json:"ids"`
	TsStart pgtype.Timestamptz `json:"ts_start"`
	TsEnd   pgtype.Timestamptz `json:"ts_end"`
}

type GetRedditPostMetricsByIDsRow struct {
	ID     string             `json:"id"`
	Title  string             `json:"title"`
	Ts     pgtype.Timestamptz `json:"ts"`
	Value  float32            `json:"value"`
	Metric string             `json:"metric"`
}

func (q *Queries) GetRedditPostMetricsByIDs(ctx context.Context, arg GetRedditPostMetricsByIDsParams) ([]GetRedditPostMetricsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getRedditPostMetricsByIDs, arg.Ids, arg.TsStart, arg.TsEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRedditPostMetricsByIDsRow
	for rows.Next() {
		var i GetRedditPostMetricsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Ts,
			&i.Value,
			&i.Metric,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRedditCommentControversiality = `-- name: InsertRedditCommentControversiality :exec
INSERT INTO reddit_comment_controversiality (id, ts, controversiality)
VALUES ($1, NOW()::TIMESTAMPTZ, $2)
`

type InsertRedditCommentControversialityParams struct {
	ID               string  `json:"id"`
	Controversiality float32 `json:"controversiality"`
}

func (q *Queries) InsertRedditCommentControversiality(ctx context.Context, arg InsertRedditCommentControversialityParams) error {
	_, err := q.db.Exec(ctx, insertRedditCommentControversiality, arg.ID, arg.Controversiality)
	return err
}

const insertRedditCommentScore = `-- name: InsertRedditCommentScore :exec
INSERT INTO reddit_comment_score (id, ts, score)
VALUES ($1, NOW()::TIMESTAMPTZ, $2)
`

type InsertRedditCommentScoreParams struct {
	ID    string `json:"id"`
	Score int32  `json:"score"`
}

func (q *Queries) InsertRedditCommentScore(ctx context.Context, arg InsertRedditCommentScoreParams) error {
	_, err := q.db.Exec(ctx, insertRedditCommentScore, arg.ID, arg.Score)
	return err
}

const insertRedditPostRatio = `-- name: InsertRedditPostRatio :exec
INSERT INTO reddit_post_ratio (id, title, ts, ratio)
VALUES ($1, $2, NOW()::TIMESTAMPTZ, $3)
`

type InsertRedditPostRatioParams struct {
	ID    string  `json:"id"`
	Title string  `json:"title"`
	Ratio float32 `json:"ratio"`
}

func (q *Queries) InsertRedditPostRatio(ctx context.Context, arg InsertRedditPostRatioParams) error {
	_, err := q.db.Exec(ctx, insertRedditPostRatio, arg.ID, arg.Title, arg.Ratio)
	return err
}

const insertRedditPostScore = `-- name: InsertRedditPostScore :exec
INSERT INTO reddit_post_score (id, title, ts, score)
VALUES ($1, $2, NOW()::TIMESTAMPTZ, $3)
`

type InsertRedditPostScoreParams struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Score int32  `json:"score"`
}

func (q *Queries) InsertRedditPostScore(ctx context.Context, arg InsertRedditPostScoreParams) error {
	_, err := q.db.Exec(ctx, insertRedditPostScore, arg.ID, arg.Title, arg.Score)
	return err
}
